Create database Customer_behavior;
use Customer_behavior;

Select *from customer limit 10;

-- What is the total revenue  generated by male vs female customer--  
Select gender , sum(purchase_amount)as revenue
from customer
group by gender;


-- Which customer used a discount but still spent more thaan the average purchase items-- 
Select customer_id, purchase_amount
from customer
where discount_applied="Yes" and purchase_amount>=(Select AVG(purchase_amount)from customer );

Select customer_id, item_purchased, purchase_amount
from customer
where discount_applied="Yes" and purchase_amount>=(Select AVG(purchase_amount)from customer );

-- Q3. Which are the top 5 products with the highest average review rating?
Select item_purchased, round(avg(review_rating),2) as Avg_product_rating
from customer
group by item_purchased
order by avg(review_rating) desc limit 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping
Select shipping_type, round(avg(purchase_amount),2)as shipping_avg
from customer
where shipping_type in('Standard','Express')
group by shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue 
-- between subscribers and non-subscribers.
Select subscription_status, count(customer_id)as total_customers,
							round(avg(purchase_amount),2) as avg_spent,
                            round(avg(purchase_amount),2)as total_revenue
from customer
group by subscription_status
order by total_revenue, avg_spent desc;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
Select item_purchased,
					round(100*sum(case when discount_applied='Yes' then 1 else 0 End)/count(*),2)as discount_rate
from customer
group by item_purchased 
order by discount_rate desc limit 6;                    

-- Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
with customer_type as (
SELECT customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM customer)

select customer_segment,count(*) AS "Number of Customers" 
from customer_type 
group by customer_segment;


-- Q8. What are the top 3 most purchased products within each category? 
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
Select subscription_status,count(customer_id)as repeat_buyers
from customer
where previous_purchases>5
group by subscription_status;

-- 10 what is the revenue contribution of each age group
select age_group, sum(purchase_amount)as total_revenue
from customer
group by age_group
order by total_revenue desc;

